# Generated by Django 5.2.1 on 2026-09-08 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('spotify', 'Spotify'), ('podchaser', 'Podchaser'), ('apple', 'Apple Podcasts'), ('podcastindex', 'PodcastIndex'), ('rss', 'RSS feed'), ('internal', 'Internal')], max_length=20)),
                ('kind', models.CharField(choices=[('charts', 'Chart scrape'), ('episodes', 'Episode sync'), ('enrichment', 'Enrichment')], default='charts', max_length=16)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='running', max_length=12)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rows_written', models.PositiveIntegerField(default=0)),
                ('slices_ok', models.PositiveIntegerField(default=0)),
                ('slices_failed', models.PositiveIntegerField(default=0)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', 'kind', '-started_at'], name='ingestion_s_source_805d81_idx')],
            },
        ),
    ]
