[uwsgi]
env = DJANGO_SETTINGS_MODULE=myproject.settings
env = UWSGI_VIRTUALENV=/venv
env = IS_WSGI=True
env = LANG=en_US.UTF-8

# İşçi qovluq
workdir = /code
chdir = /code

# Django tətbiqinin əsas modulu
module = myproject.wsgi:application

# UWSGI Master prosesi
master = True

# Proses ID faylı
pidfile = /tmp/app-master.pid

# Çıxış fayllarını sil
vacuum = True

# Maksimum sorğu sayı
max-requests = 5000

# Proseslər
processes = 5
cheaper = 2
cheaper-initial = 5

# Giriş/Giriş istifadəçiləri
gid = root
uid = root

# HTTP soket
http-socket = 0.0.0.0:8000

# Statistik məlumat üçün
stats = 0.0.0.0:8001

# Harakiri (timeout) parametri
harakiri = 60
print = Your timeout is %(harakiri)

# Static fayl xəritəsi
static-map = /static=%(workdir)/static
static-map = /media=%(workdir)/media

# Thread dəstəyi aktivləşdir
enable-threads = true
