# Generated by Django 5.2.1 on 2026-09-08 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('spotify', 'Spotify'), ('podchaser', 'Podchaser'), ('apple', 'Apple Podcasts'), ('podcastindex', 'PodcastIndex'), ('rss', 'RSS feed'), ('internal', 'Internal')], default='internal', max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160)),
                ('external_id', models.CharField(blank=True, default='', max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='podcasts.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['source', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rss_url', models.URLField(blank=True, default='', max_length=1000)),
                ('apple_id', models.CharField(blank=True, default='', max_length=32, verbose_name='Apple/iTunes collectionId')),
                ('podcastindex_id', models.CharField(blank=True, default='', max_length=32)),
                ('podcastindex_guid', models.CharField(blank=True, default='', max_length=64)),
                ('podchaser_id', models.CharField(blank=True, default='', max_length=32)),
                ('spotify_id', models.CharField(blank=True, default='', max_length=64)),
                ('match_key', models.CharField(blank=True, db_index=True, default='', help_text="normalised '<title>|<publisher>' fallback de-dupe key", max_length=400)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, default='', max_length=280)),
                ('description', models.TextField(blank=True, default='')),
                ('publisher', models.CharField(blank=True, default='', max_length=300)),
                ('author', models.CharField(blank=True, default='', max_length=300)),
                ('image_url', models.URLField(blank=True, default='', max_length=1000, verbose_name='cover image URL')),
                ('website_url', models.URLField(blank=True, default='', max_length=1000)),
                ('language', models.CharField(blank=True, default='', max_length=16)),
                ('country', models.CharField(blank=True, default='', max_length=8)),
                ('explicit', models.BooleanField(default=False)),
                ('itunes_type', models.CharField(blank=True, default='', max_length=16)),
                ('rating_average', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rating_count', models.PositiveIntegerField(blank=True, null=True)),
                ('publish_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Every two weeks'), ('monthly', 'Monthly'), ('sporadic', 'Sporadic'), ('', 'Unknown')], default='', max_length=16)),
                ('total_episodes', models.PositiveIntegerField(default=0)),
                ('last_published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('enrichment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially enriched'), ('done', 'Enriched'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12)),
                ('enriched_at', models.DateTimeField(blank=True, null=True)),
                ('enrichment_sources', models.JSONField(blank=True, default=list)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('episodes_synced_at', models.DateTimeField(blank=True, null=True)),
                ('feed_etag', models.CharField(blank=True, default='', max_length=250)),
                ('feed_last_modified', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('first_seen_source', models.CharField(blank=True, choices=[('spotify', 'Spotify'), ('podchaser', 'Podchaser'), ('apple', 'Apple Podcasts'), ('podcastindex', 'PodcastIndex'), ('rss', 'RSS feed'), ('internal', 'Internal')], default='', max_length=20)),
                ('categories', models.ManyToManyField(blank=True, related_name='podcasts', to='podcasts.category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guid', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=600)),
                ('description', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('episode_number', models.PositiveIntegerField(blank=True, null=True)),
                ('season_number', models.PositiveIntegerField(blank=True, null=True)),
                ('episode_type', models.CharField(blank=True, default='', max_length=16)),
                ('explicit', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('audio_url', models.URLField(blank=True, default='', max_length=1500)),
                ('audio_length_bytes', models.BigIntegerField(blank=True, null=True)),
                ('audio_type', models.CharField(blank=True, default='', max_length=60)),
                ('external_ids', models.JSONField(blank=True, default=dict)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('spotify', 'Spotify'), ('podchaser', 'Podchaser'), ('apple', 'Apple Podcasts'), ('podcastindex', 'PodcastIndex'), ('rss', 'RSS feed'), ('internal', 'Internal')], default='rss', max_length=20)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='podcasts.podcast')),
            ],
            options={
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['source', 'slug'], name='podcasts_ca_source_620fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='podcasts_ca_slug_de34ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('source', 'slug'), name='uniq_category_source_slug'),
        ),
        migrations.AddIndex(
            model_name='podcast',
            index=models.Index(fields=['title'], name='podcasts_po_title_b6422d_idx'),
        ),
        migrations.AddIndex(
            model_name='podcast',
            index=models.Index(fields=['publisher'], name='podcasts_po_publish_c29306_idx'),
        ),
        migrations.AddIndex(
            model_name='podcast',
            index=models.Index(fields=['language'], name='podcasts_po_languag_a17b08_idx'),
        ),
        migrations.AddIndex(
            model_name='podcast',
            index=models.Index(fields=['enrichment_status', 'enriched_at'], name='podcasts_po_enrichm_659a01_idx'),
        ),
        migrations.AddIndex(
            model_name='podcast',
            index=models.Index(fields=['episodes_synced_at'], name='podcasts_po_episode_ae1bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='podcast',
            index=models.Index(fields=['-last_published_at'], name='podcasts_po_last_pu_e450ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='podcast',
            constraint=models.UniqueConstraint(condition=models.Q(('rss_url', ''), _negated=True), fields=('rss_url',), name='uniq_podcast_rss_url'),
        ),
        migrations.AddConstraint(
            model_name='podcast',
            constraint=models.UniqueConstraint(condition=models.Q(('apple_id', ''), _negated=True), fields=('apple_id',), name='uniq_podcast_apple_id'),
        ),
        migrations.AddConstraint(
            model_name='podcast',
            constraint=models.UniqueConstraint(condition=models.Q(('podcastindex_id', ''), _negated=True), fields=('podcastindex_id',), name='uniq_podcast_pi_id'),
        ),
        migrations.AddConstraint(
            model_name='podcast',
            constraint=models.UniqueConstraint(condition=models.Q(('podcastindex_guid', ''), _negated=True), fields=('podcastindex_guid',), name='uniq_podcast_pi_guid'),
        ),
        migrations.AddConstraint(
            model_name='podcast',
            constraint=models.UniqueConstraint(condition=models.Q(('podchaser_id', ''), _negated=True), fields=('podchaser_id',), name='uniq_podcast_pc_id'),
        ),
        migrations.AddConstraint(
            model_name='podcast',
            constraint=models.UniqueConstraint(condition=models.Q(('spotify_id', ''), _negated=True), fields=('spotify_id',), name='uniq_podcast_spotify_id'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['podcast', '-published_at'], name='episode_podcast_pubdate_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['-published_at'], name='episode_pubdate_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['podcast', '-id'], name='episode_podcast_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('podcast', 'guid'), name='uniq_episode_podcast_guid'),
        ),
    ]
