# Generated by Django 5.2.1 on 2026-09-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_search_trgm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': [models.OrderBy(models.F('published_at'), descending=True, nulls_last=True), '-id']},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='podcasts_ca_source_620fd2_idx',
        ),
        migrations.RemoveIndex(
            model_name='episode',
            name='episode_podcast_pubdate_idx',
        ),
        migrations.RemoveIndex(
            model_name='episode',
            name='episode_podcast_id_idx',
        ),
        migrations.AlterField(
            model_name='podcast',
            name='enrichment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially enriched'), ('done', 'Enriched'), ('failed', 'Failed')], default='pending', max_length=12),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(models.F('podcast'), models.OrderBy(models.F('published_at'), descending=True, nulls_last=True), models.OrderBy(models.F('id'), descending=True), name='episode_podcast_pubdate_idx'),
        ),
    ]
